### ISSUE TITLE
Class App\repositories\ApplicationFormRepository\ApplicationFormRepository does not exist

### ISSUE THREAD

**Issue by kalkoen** [esac-ic/esac.nl#255] opened 2021-11-01 16:51 UTC
The Events management page does not seem to work as long as App/repositories/ApplicationFormRepositories folder is called this way.
Even though ApplicationFormRepository has namespace App\repositories\ApplicationFormRepository, the subfolder needs to be called ApplicationFormRepository as well  for me.

Using: Laragon Full 5.0.0
Steps to reproduce: follow instructions from README, then log in with test account and go to events manage page.

Not very experienced with Laravel, likely something to do with my development environment.

**Comment by wouterbles** [comment] 2021-11-06 22:18
Thanks for your feedback! I haven't tried reproducing the issue locally yet, but I think this could be due to you using a newer version of Composer/PHP.

Would you be interested in joining the IC? It would be nice to get development going again :)

**Comment by wouterbles** [comment] 2022-06-02 15:25
Should be fixed

**Closed by wouterbles** 2022-06-02 15:25 UTC
